[general]
description = "SDL simulator of the AdaFruit PyGamer console"
website = "https://github.com/Fabien-Chouteau/pygamer-simulator"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = ["BSD 3-Clauses"]
tags = ["pygamer", "adafruit", "game", "console", "simulator"]

project-files = ["pygamer_simulator.gpr"]

["0.1.0"]
origin = "https://github.com/Fabien-Chouteau/pygamer-simulator/releases/download/v0.1.0/pygamer-simulator-0.1.0.zip"
origin-hashes = ["sha512:6791f2e1ec0a60d8dcf70a0feaf9e755ee1079fdc51fad61e0475cf89b98e28f6363792aac3ff7881a2d1258c3abae6c3873b3f9827f8710e0d0ade2b4d27c36"]
["0.1.0".depends-on]
sdlada = "^2.3.1"
hal = "^0.1.0"

["0.1.1"]
origin = "https://github.com/Fabien-Chouteau/pygamer-simulator/releases/download/v0.1.1/pygamer-simulator-0.1.1.zip"
origin-hashes = ["sha512:e859696b74e19d5ff1285e32f3ad6cb24964ec52244836ba6505ff8b765c4c64a3d09e71a19a6f1f48a2c682e244e5c25def1f24cd284b0ee2b4f26495e4737d"]
["0.1.1".depends-on]
sdlada = "^2.3.1"
hal = "^0.1.0"

