name = "librtaudio"
description = "Common API for realtime audio input/output across multiple platforms"

maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[external]]
kind = "system"
   [external.origin."case(distribution)"]
   "debian|ubuntu" = ["librtaudio-dev"]
   "msys2"         = ["mingw-w64-x86_64-rtaudio"]
   "arch|fedora"   = ["rtaudio"]
