name = "atomic"
description = "Standalone Ada/SPARK bindings to GCC atomic built-ins"
version = "0.4.0"

licenses = "MIT"
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/atomic"
tags = ["atomic", "spark", "embedded", "nostd"]

[configuration.variables]
Backend = {type = "Enum",  values = ["Intrinsic", "armv6m"], default = "Intrinsic"}

[origin]
commit = "4ff1638c1cd27f220cccd6ed2d13095fef78925d"
url = "git+https://github.com/Fabien-Chouteau/atomic.git"

