[general]
description = "GNAT Components Collection - iconv binding"
licenses = ["GMGPL 3.0"]
authors = ["AdaCore"]
maintainers = ["derodat@adacore.com"]
maintainers-logins = ["pmderodat"]
website = "https://github.com/adacore/gnatcoll-bindings"
tags = ["gnatcoll", "bindings", "iconv", "i18n"]
project-files = ["iconv/gnatcoll_iconv.gpr"]

[general.gpr-externals]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]
GNATCOLL_BUILD = ["DEBUG", "PROD"]

# GNATCOLL_ICONV_OPT should be empty on linux but gprbuild consider empty
# environement variable as not being set. So we use a harmless linker option to
# have a non-empty GNATCOLL_ICONV_OPT.
[general.gpr-set-externals.'case(os)']
linux   = { GNATCOLL_ICONV_OPT = "-v" }

[[general.actions]]
type = "post-fetch"
command = ["sed", "-i", "s/\"LIBRARY_TYPE\")/\"LIBRARY_TYPE\", \"static\")/", "iconv/gnatcoll_iconv.gpr"]

["9999.0.0"]
origin = "git+https://github.com/AdaCore/gnatcoll-bindings.git@7b0376a4443b9bc0b0df63b9e94b03f82f8af5ec"
["9999.0.0".depends-on]
gnatcoll = "9999.0.0"
["9999.0.0".depends-on.'case(os)'.windows]
libiconv = "*"
