[general]
description = "GNAT Components Collection - Core packages"
licenses = ["GMGPL 3.0"]
authors = ["AdaCore"]
maintainers = ["derodat@adacore.com"]
maintainers-logins = ["pmderodat"]
website = "https://github.com/adacore/gnatcoll-core"
tags = ["gnatcoll", "json", "email", "refcount", "projects", "gpr", "vfs"]
project-files = ["gnatcoll.gpr"]

[general.gpr-externals]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]
GNATCOLL_BUILD = ["DEBUG", "PROD"]

[general.gpr-set-externals.'case(os)']
linux   = { GNATCOLL_OS = "unix" }
windows = { GNATCOLL_OS = "windows" }
macos   = { GNATCOLL_OS = "osx" }

[general.gpr-set-externals]
GNATCOLL_VERSION = "9999.0.0"

["9999.0.0"]
origin = "git+https://github.com/AdaCore/gnatcoll-core.git@fa4244fd57a52bd7d37ac1a8e291ceb24b15bb50"
["9999.0.0".depends-on]
libgpr = "9999.0.0"
