name = "usb_embedded"
description = "An Ada USB stack for embedded devices"
version = "0.3.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/usb_embedded"
licenses = "BSD-3-Clause"
tags = ["embedded", "usb", "hid", "midi", "nostd"]

[[depends-on]]
hal = "~0.3"
bbqueue = "~0.3.0"

[configuration.variables]
Control_Buffer_Size = {type = "Integer", first = 256, default = 256 }
String_Buffer_Size = {type = "Integer", first = 0, default = 256 }
Max_Strings = {type = "Integer", first = 0, default = 10 }
Event_Log_Buffer_Size = {type = "Integer", first = 0, default = 0 }

[origin]
commit = "6c2c7b96aef581c6567149091c4a8577c1096f79"
url = "git+https://github.com/Fabien-Chouteau/usb_embedded.git"

