name = "midi"
description = "Library to encode and decode MIDI messages"
version = "0.2.0"
licenses = "MIT"
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/MIDI"
tags = ["midi", "embedded", "nostd"]

[[depends-on]]
hal = "~0.3.0"
bbqueue = "~0.3.0"

[origin]
commit = "e251566c42be376cca1248c3bc4bfa2ad0a0fa56"
url = "git+https://github.com/Fabien-Chouteau/MIDI.git"
