[general]
description = "Simple DirectMedia Layer development files - TTF"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libsdl2-ttf-dev"]
    'msys2' = ["mingw-w64-x86_64-SDL2_ttf"]
