[general]
description = "The XML/Ada toolkit"
licenses = ["GPL 3.0"]
authors = ["AdaCore"]
website = "https://github.com/AdaCore/xmlada"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

project-files = ["distrib/xmlada.gpr", "dom/xmlada_dom.gpr",
                 "sax/xmlada_sax.gpr", "input_sources/xmlada_input.gpr",
                 "schema/xmlada_schema.gpr", "unicode/xmlada_unicode.gpr"]

[general.gpr-externals]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]
XMLADA_BUILD_MODE = ["distrib", "Debug", "Production", "profile", "coverage", "nochecks"]

[[general.actions]]
type = "post-fetch"
command = ["sh", "configure"]

['16.1']
origin = "https://github.com/AdaCore/xmlada/archive/xmlada-16.1.tar.gz"
origin-hashes = ["sha512:a2d454745af202a17e9bcfc3cd8226010652ab46c4699e7d374868966c6ac8e20d9fdee45ccc52c8ee99ca9ead0e979c401b1eff1647293308b975c96017692e"]

['9999.0.0']
origin = "git+https://github.com/AdaCore/xmlada.git@2c7b96aac7e10a383e05c670cfe5ec9f07f947f2"
